Update README.rst
JazzCore/python-pdfkit pull request #165
Opened 2020-07-30 01:33 UTC by NullYing

```
Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.
```

2020-08-20 10:16 UTC, Lucurus requested changes
I would suggest changing the brew cask command.

2020-08-20 10:16 UTC, Lucurus commented on README.rst
> +	$ brew install homebrew/cask-cask/wkhtmltopdf
```suggestion
	$ brew cask install wkhtmltopdf
```

As outlined in https://github.com/JazzCore/python-pdfkit/issues/149#issuecomment-677507216 brew specifies the correct method as `brew cask install`.



I have also created #168 as I hadn't seen this one but only one is necessary so I can close mine as well.

2020-10-27 10:35 UTC, ArtemBernatskyy commented
it seems that this repo has died, xD

2020-10-27 10:36 UTC, BastianZim commented
Yeah, unfortunately.

2021-03-19 16:32 UTC, JazzCore commented
``brew cask install wkhtmltopdf`` does not work for me on current MacOS, but ``brew install homebrew/cask/wkhtmltopdf`` does, fixed in #173, thanks guys and sorry that it took so long to get to it.

2021-03-19 16:32 UTC, closed without merging